# Generated by Django 5.2.8 on 2025-12-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_historialubicacion_monitoreo_h_ubicaci_ab6b87_gist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialubicacion',
            name='bateria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
